spring.profiles.active: dev
---
spring.config.activate.on-profile: local

spring.datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:file:./db;AUTO_SERVER=TRUE
  username: test
  password: 1234
spring.h2:
  console:
    path: /h2-console
    enabled: true

spring.jpa:
  show-sql: true
  open-in-view: false
  hibernate:
    ddl-auto: create-drop
    use-new-id-generator-mappings: false

spring.jackson.property-naming-strategy: SNAKE_CASE

---
spring.config.activate.on-profile: dev

spring.datasource:
  url: "jdbc:mariadb://52.78.41.216:3306/emart2_redirect_db?characterEncoding=UTF-8&serverTimezone=KST"
  username: "emart"
  password: "123"
  driver-class-name: org.mariadb.jdbc.Driver

spring.jpa:
  database: mysql
  database-platform: org.hibernate.dialect.MariaDB10Dialect
  show-sql: true
  hibernate.ddl-auto: update

spring.jpa.properties.hibernate.format_sql: true

---
spring.config.activate.on-profile: prod
