server.servlet.context-path: "/admin"
spring.mvc.hiddenmethod.filter.enabled: true
logging.level.org.hibernate.type.descriptor.sql: trace

spring:
  profiles:
    include:
      - auth
      - dev_maria

server:
  port: 8081
